### ISSUE TITLE
Unbound namespace in JSON FullView rendering

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#676]
```
[Fatal Error] :31:467: The prefix "dcterms" for element "dcterms:rightsHolder" is not bound.
2012-09-11 09:35:11,975 - [ERROR] - CultureHub: Exception while rendering view tib_1.0.0 for record brabantcloud_museum-de-wieger_A 83264
org.xml.sax.SAXParseException: The prefix "dcterms" for element "dcterms:rightsHolder" is not bound.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:249) ~[na:1.6.0_26]
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284) ~[na:1.6.0_26]
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:124) ~[na:1.6.0_26]
    at core.rendering.ViewRenderer.renderRecordWithView(ViewRenderer.scala:87) ~[web-core_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at core.rendering.ViewRenderer.renderRecord(ViewRenderer.scala:80) ~[web-core_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at core.rendering.RecordRenderer$.renderMetadataRecord(RecordRenderer.scala:153) [web-core_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at core.rendering.RecordRenderer$.renderMetadataRecord(RecordRenderer.scala:96) [web-core_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at core.rendering.RecordRenderer$.getRenderedFullView(RecordRenderer.scala:51) [web-core_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
    at core.search.SearchService.getRenderedFullView(SearchService.scala:150) [web-core_2.9.1-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
```

**Comment by geralddejong** [comment]
So far I have no idea why this is happening but it's worth mentioning that there is now already a version 1.0.2 for TIB.

**Comment by geralddejong** [comment]
Looks to me like the ViewRender's renderRecord doesn't have "dcterms" in its namespaces map.

**Comment by manuelbernhardt** [comment]
My current theory as to what happens is that the original record which results from the mapping has a different dcterms declaration than the one in the record definition, but that is just a hypothesis. I'll test it now.

**Comment by manuelbernhardt** [comment]
This was fixed a while back
